### ISSUE TITLE
Permissions error when ending instance

### ISSUE THREAD

**Issue by eduardoaw** [aws-samples/amazon-cloudwatch-auto-alarms#1]
Upon terminating an instance the permissions error log is generated for the Lambda function:

[ERROR]	2021-01-21T16:50:16.960Z
Error deleting alarms for instance i-xxxxxxxxxxxxxxx!: An error occurred (AccessDenied) when calling the DescribeAlarms operation: User: arn:aws:sts::xxxxxxxxxxxx:assumed-role/cloudwatch-auto-alarms-CloudWatchAutoAlarmLambdaRo-xxxxxxxxxxx/CloudWatchAutoAlarms is not authorized to perform: cloudwatch:DescribeAlarms on resource: arn:aws:cloudwatch:us-east-1:xxxxxxxxxxxxxxxx:alarm:* |

**Comment by knizami** [comment]
Hi @eduardoaw - Thanks for raising this.  This has been fixed in commit 047ecb0d8568b8af9e64f7a85eba12eac24cbb70.
