### ISSUE TITLE
Alarms not creating

### ISSUE THREAD

**Issue by anmolk17** [aws-samples/amazon-cloudwatch-auto-alarms#5]
Hello,

After performing steps in part 1, i am able to see metrics under CWagent namespace but there are no alarms created.
When i checked logs of lambda function, below error was found.
![cloudwatch_error](https://user-images.githubusercontent.com/54226811/116227364-592aca00-a754-11eb-8fd6-66901e419f14.JPG)

Can anyone help me on this.

Thanks
Anmol

**Comment by knizami** [comment]
Hello,

It appears that the Lambda function isn't loading correctly.  When you
follow the deployment steps and create the zip file, ensure that the files
are under no subdirectories.  When you unzip the package (zip file) that
you created for deployment, all the code should be in the root folder.

**Comment by anmolk17** [comment]
Oh man !! thanks for the help. It worked now.
Will be working on advance part now.
